### PR TITLE
Updated to Unreal Engine 4.15

### PR DESCRIPTION
**Pull request by TheZoc**

### CODE REVIEW

**Comment by TheZoc** [comment]
This is fully updated and functional with Unreal Engine 4.14.
The source code contained in this version also works with UE4.13, if the need arise.

**Review by axi430 — APPROVED** [review]

**Comment by miguelemosreverte** [comment]
Cool!

**Comment by bmcgauley** [comment]
I implemented your version into 4.14 but now whenever I drag out the manofwar PIE crashes, did you have this issue as well?

**Comment by TheZoc** [comment]
There are a few more improvements on my fork that I will only submit after this PR is accepted / merged, since it touches in other assets beyond 4.14 support.
You might want to check if it fixes your issue :)

**Comment by ericwomer** [comment]
TheZoc could you test it with OpenGL4 on windows, and see it it renders correctly? I cant get it right on linux and I want to see if its a linux bug or an OpenGL bug.

**Comment by ericwomer** [comment]
I don't think this project is updated anymore, as there trello isn't updated anymore ant the last release is 4.12.

**Comment by victor-vexargames** [comment]
Salamanderrake, I think the guys who were working on this got busy but people like Zoc are still keeping running. Nobody has said on the main Epic thread that the project is dead so I just assume they will get back to it when they have time. For myself I cleaned up the project and removed all the content I didn't need just wanted the water.

**Comment by Bmahoneyff7** [comment]
I'm a real beginner on GitHub (second time even opening it) and all I see to download is the 4.12 version. Is there a way to access the 4.14 updates without spending too much time learning GitHub? I'm kind of a time constraint while that water is amazing I can't spend too much time on it. Thanks!

**Comment by miguelemosreverte** [comment]
@TheZoc  made changes that makes the project 4.14 compatible.

Go here https://github.com/TheZoc/OceanProject
and clone the project. Even though it says that the default branch is called 4.12, that is actually the branch proposed for the PR, which says to be 4.14 compatible. So yeah, clone it and you are good to go. :)

**Comment by bmcgauley** [comment]
Yep, I can confirm Bmahoneyff7 that this is indeed 4.14 compatible and works like a charm even though it says 4.12. As miguelemosreverte has stated it's just a proposed change to the main branch or original project.

**Comment by ericwomer** [comment]
It works fine, I assume with DirectX but not with OpenGL and therefore no Linux or Mac Support.

**Comment by TheZoc** [comment]
Happy new year guys!

As far as I recall, the code has no HLSL or GLSL instructions directly, thus, it should work on both of APIs. 
I'll need to check the specific material shaders, though, if there are custom nodes.

According to [this link](https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/ExpressionReference/Custom/), it will need to be converted from HLSL to GLSL.

I can't do it now, but I will definitely add that eventually. If you end up porting, it would be awesome to have a guide on what was changed, so I can merge and make it cross platform :)

Cheers!

**Comment by ericwomer** [comment]
@TheZoc So it could be a custom expression that is causing the issues? All epic shaders (hlsl) are converted to glsl via hlscc when the editor compiles shaders. This will never work with opengl3, but only opengl4 but there are some issues still around that still haunt GL4 based mostly on mis-conceptions about OpenGL4 and sm5 features. Like the samples limit (artifically still stuck on 16 max for opengl4, which its really the min number of shader samples that opengl4 can handle) The plugin works on linux, but it does not render correctly.

**Comment by ericwomer** [comment]
@TheZoc this is what I see, http://imgur.com/LH5u7GH what does  the plugin actually use to render the ocean?

**Comment by TheZoc** [comment]
@salamanderrake Sadly, I didn't have time to check all of that yet - this weekend is impossible for me, at least.
I'm interested to make this work on OpenGL since I plan to use it under Mac and Linux! Still, I'm covering too many areas on my game project to be able to stop everything and take a good look into this right now.

If you have any leads on this, I invite you to fork and submit PRs with fixes to my fork, to keep everything centralized/working.

I'd start looking at the water material shader itself and search for any custom nodes.

Do you have more info on how epic shaders get translated to glsl? Is it automatic? Does it output a log?
Maybe it's a simple expression it's failing to understand.

The link I submitted on my previous comment has a notice they don't get translated, but might be outdated information, as often happens in UE4 documentation.

Looking forward to hear back from you! :)

**Comment by ericwomer** [comment]
@TheZoc Its automatically converted from UE4 internal/HLSL to GLSL, but for mac you would want to use metal, as OpenGL3 will not work with this at all. For OpenGL3/4 its converted via hlscc compiler that is provided by Epic, but with custom nodes there may be some things that was done that hlslcc may not convert/compile correctly. Sometimes its a setting that triggers a shader error. Like if you had a translucent shiny material that you wanted to tessellate (its in the node material setting) the bloom would over kill it because of a UE4 shader issue. So it would look like this [http://imgur.com/Zz2GN2v](url) but was fixed with this section on a shader file. https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Shaders/BasePassTessellationShaders.usf#L81 . which fixed the over bloom and the tessellation of the water material there.

**Comment by ericwomer** [comment]
@TheZoc Oh, if you get chance, you should beadle to start the editor in OpenGL4 mode with a command line switch -opengl4, you can start it from the cmd.exe line or create a launcher with that switch. UE4Editor.exe -opengl4

**Comment by ericwomer** [comment]
@TheZoc https://docs.unrealengine.com/latest/INT/Programming/Rendering/ShaderDevelopment/HLSLCrossCompiler/index.html

**Comment by ericwomer** [comment]
@TheZoc Here is me starting up the editor with OceanProject. https://dl.dropboxusercontent.com/u/71062164/unrealengine/OceanPlugin/first-run-shader-compile-build.txt

Also I was able to get somewhere when I disabled tessellation for the Ocean materials, but this project needs tessellation but its a start though. I will file a bug with epic here in a bit.

**Comment by TheZoc** [comment]
@salamanderrake Apparently, the HLSL Cross Compiler doesn't support custom nodes in the material editor. Those nodes will need to be converted manually to HLSL and added to USF files. This will probably prevent this project to be used as a plugin (this is something that must be looked into).

A simpler (but not super optimized) solution would be to have two materials (one with HLSL and other with GLSL shader code into the material editor) and have the blueprint code to select which material to use on the fly. This is the hackish-easier approach, but it's not ideal.

All of that I'm saying without going into detail on how the current material works. There's a chance that the custom nodes in there use standard instructions that could be replaced with nodes and solve our problems :)

Since you seem to be more fluent in shader language, do you mind investigating a bit more? I'm sorry I can't dive into the code right now, I'm kinda far from my computer.

Btw, I'll try tomorrow or so to open UE4 with the `-opengl4` flag and see how it goes :)

**Comment by ericwomer** [comment]
@TheZoc https://answers.unrealengine.com/questions/352034/bug-report-sm5-on-linux-is-limited-to-16-texture-s.html

**Comment by bmcgauley** [comment]
@TheZoc Quick question for you, our projects gotten down to the point of testing multiplayer and testing on several systems and we're doing some low spec testing right now.  Can you confirm if buoyancy "NEEDS" physx or not?  What I mean is that we loaded the game up on a mid spec laptop with intel graphics and without the ship in the levels it does indeed load. If we put the ship (using just the manofwar) in the level, it crashes with a reference to the engines physics cpp file.  The errors pretty vague but this is my only assumption based on our tests is that it has to be a physx capable card that runs it. which would mean either nvidia or have an amd run off the cpu for physx.  Or am I totally wrong and it's something else that isn't fixed yet in the ocean plugin?

Thanks for any help, we're really struggling here and we're over our limit for testing :/

**Comment by TheZoc** [comment]
@salamanderrake I forgot my build was broken by a new feature I'm adding. Sorry to make you wait more time :(

@bmcgauley there's more than one version of Man of war in there, there's a chance you're using the broken one. I think I removed the broken one in my fork, mind checking that?
Also, PhysX runs on the processor, just install the software on the notebook :)
Lastly, can you show the trace stack or any relevant parts in the code? Might help pinpointing the issue :)

**Comment by bmcgauley** [comment]
@TheZoc Ok I'll get the stack if it does it again, I'm going to test again with the other boat version.  I didn't realize one was broken and one worked.  I did install physx on the test machine which is why I had gotten confused it was still pointing the error to the same area.  I'll copy the log if it happens with the other boat, but that makes sense, hopefully it wont happen :)

**Comment by TheZoc** [comment]
@bmcgauley please report back with your findings, might help anyone who hit the same problem (including myself in a near future :) )

**Comment by bmcgauley** [comment]
I'm doing my best to try a few things right now, I'm still having the error with every manofwar copy I have at the moment. (I only have 3, 1 is a blank original with bp's erased, the other is an intact copy and the last is another modified blank.)  I've spent all night testing, and I'm doing one more test pass right now to see if maybe physics are being calculated "too soon" and delaying it by 10 seconds.  I'll report on anything I find and any resolutions though :)

**Comment by bmcgauley** [comment]
"Assertion failed: IsInGameThread() [File:C:\Program Files (x86)\Epic Games\Unreal Engine-4.14\Engine\Source\Runtime\Engine\Private\PhysicsEngine\PhysScene.cpp][Line: 230]  is the only stack trace I get, and yes it's still happening even when delaying enabled physics.  This only happens when the ship is in the scene and not on my main dev machines (which are probably a little overpowered for the job.)  This only happens on our lower spec testing laptop.  Physx is installed, directx, all the engine required files, ect.  If I take out the manofwar, it works fine.  Sad part is is that if it's to do with the buoyancy that will wreck our game (as our game is built on sailing so even if switching the mesh out, we will still need the core to work. with another mesh.)  

The laptop we're testing on is windows 10 pro 64 bit, intel cor i7-4610M@3.0GHz with 8GB ram.  Graphics is an intel HD graphics 4600.

**Comment by bmcgauley** [comment]
so, after much headbanging against the wall it turns out the root of my problem has all come down to glitchy .apex files (was using customized sails, not the projects ones.)  Can anyone confirm that in 4.14 the stock sails that come with this project are not suffering from the apex failures of UE4.14 and physx 3.4?  Running some tests myself but if someone can just confirm as well it'd really help.

**Review by StartOrigin — CHANGES_REQUESTED** [review]
Please upgrade to version 4.15

**Comment by kpd200081** [comment]
What about 4.15 update?

**Comment by TheZoc** [comment]
Sorry for the long delay, I updated it to UE 4.15 😁

**Comment by miguelemosreverte** [comment]
Fantastic

2017-03-30 2:46 GMT-03:00, TheZoc <notifications@github.com>:

**Pull request closed without merging**
