### PR TITLE
Update for UE 4.19+

### PR DESCRIPTION
**Pull request by reapazor**

### CODE REVIEW

**Comment by TheZoc** [comment]
Hello @reapazor !

Thank you for submitting this PR!

I don't see yet an option to use or preview the 4.19 branch. Is this change aimed at those using the engine built from the source?

Thank you very much in advance!

**Comment by reapazor** [comment]
Hey! Yes this is a change for 4.19 / 4.20 - currently only available by source. I guess cue it up for later? Lol

--
Matthew Davey
dotBunny
________________________________

**Comment by neico** [comment]
Labelz, Milestonez!

Though a milestone is probably a bit exaggerated.  
But a label such as `next` or so should be fine

**Comment by reapazor** [comment]
I can't seem to be able to apply any labels / milestones :(

**Comment by neico** [comment]
Only people with write access on the repo can create and assign those...

**Comment by reapazor** [comment]
The 4.19 Rocket Build is now available for testing :)

**Comment by TheZoc** [comment]
Added suggested label 😁

**Comment by EvoPulseGaming** [comment]
4.19 has been released in launcher. This was beautiful timing!

**Comment by reapazor** [comment]
It’s almost like I knew some how ;)

--
Matthew Davey
dotBunny
________________________________

**Comment by EvoPulseGaming** [comment]
:)
The "Make TimeScaleMultiplier actually do something" should be merged into 4.18,4.19
And this should be merged for 4.19
4.19 had major LOD/Tesselation for Landscape rendering pipeline optimizations done... I wonder if the ocean could somehow be set as a "Landscape"?
"tessellation with a factor of 3 in a 255x255x2 map with a big view of most of the landscape (light in the back to have the worst case for shadow), before it was around 9-10 fps on a GTX 1060, right now i'm closer to 30-40"
https://forums.unrealengine.com/development-discussion/content-creation/35763-landscape-lighting-issue
That was just the first part of the rendering pipeline, they are doing the shadows part for it in 4.20!

**Comment by TheZoc** [comment]
Somehow, I forgot to merge #58 earlier, my apologies.

This one will only be merged after 4.19 is out of preview, to avoid confusing most of the users. It is generally easier to keep the master compatible with the latest (non-beta) version :D

I don't know about tessellation on terrains, sadly, neither if they could be applied here. I wonder if @dotcamdev knows more about it :)

**Review by LiviuChirca — APPROVED** [review]

**Comment by TheZoc** [comment]
I'm downloading UE4.19 now. I should be able to merge after the download completes :)

**Comment by TheZoc** [comment]
Merged! Thank you very much for the PR, @reapazor ! 😁

**Pull request merged**
