### PR TITLE
Make TimeScaleMultiplier actually do something

### PR DESCRIPTION
**Pull request by danielprejean**
Pretty self-explanatory...

### CODE REVIEW

**Review by TheZoc — APPROVED** [review]

**Comment by TheZoc** [comment]
@bluefalcon26 Sorry for the delay!
Thank you for submitting this fix!

**Comment by EvoPulseGaming** [comment]
While this fixes the Time scale, there seems to be an issue with daylight saving time now?
The sun moves at 2x the speed, while the moon moves normally...

**Comment by TheZoc** [comment]
I missed this comment. Is this still an issue?

**Comment by EvoPulseGaming** [comment]
yes, dst with the fixed time scale, makes the sun move fast

**Comment by dotcamdev** [comment]
[BUG: DST Makes the Sun Increase Speed](https://trello.com/c/w5q03l83/62-bug-dst-makes-the-sun-increase-speed)

**Comment by dotcamdev** [comment]
[BUG: DST Makes the Sun Increase Speed](https://trello.com/c/w5q03l83/62-bug-dst-makes-the-sun-increase-speed)

**Pull request merged**
