### PR TITLE
Check for null ref crash on actors without meshes!

### PR DESCRIPTION
**Pull request by EvoPulseGaming**

### CODE REVIEW

**Comment by Mellnik** [comment]
Thank you!

**Comment by EvoPulseGaming** [comment]
Was this an issue you were having?

**Comment by dotcamdev** [comment]
@saschaelble Looks good, I will merge this in when I finish my bug fixing, should be up within the next couple of days.

On a side note, thank you so much for everything you have done on this project, and for helping so many people fix their issues. I will gladly add you as a contributor to this project if you'd like, just let me know!

Thanks again! :)

**Review by dotcamdev — APPROVED** [review]
Looks good!

**Pull request merged**
