### PR TITLE
- Updated to Unreal Engine 4.17

### PR DESCRIPTION
**Pull request by TheZoc**
* Changes for the Unreal Engine 4.15 PR (Fixes some issues with current master)
     - Updated to Visual Studio 2017
     - Added user folder from VS2017 to .gitignore
     - Fixed many errors and warnings
     - Changed M_Ocean_SSR Reflection Cubemap param from Color to Linear Color
     - Changed ThirdPersonCharacter GrabComponentAtLocation node with 
GrabComponentAtLocationWithRotation. Left the rotation data as default (0,0,0).
     - Deleted broken BP_SkyOLD (Replaced with BP_Skydome). Removed together auxiliary WB_SkyOLD_HUD debug widget.
     - Deleted Old versions of the ManOfWar meshes (they were messing up the build tool and weren't referenced anywhere)
     - Updated BP_Rivertool, replacing the deprecated functions
     - Replaced View.ViewSizeAndSceneTexelSize.xy with an external node in M_PP_RadialBlur
     - Updated OceanShaderEnum.uasset to UE4.15
     - Updated README.md to show features added in UE4.12 and that it is updated to UE4.15
     - Merged with base OceanProject repository
     - Merged my changed with base OceanProject repository

.
* Changes for the Unreal Engine 4.17 PR
     - Updated uplugin project file to the new stricter standards
     - Bumped plugin internal version to 1.1
     - Updated all .cs files to the latest format/version
     - Updated conflicting assets
     - Some code cleanup

### CODE REVIEW

**Comment by TheZoc** [comment]
Since my pull request was not merged, I figured it would be because it wasn't squashed in a single commit, so here it is again.

As a plus (that I forgot to include in the above changelog), I removed RuntimeMeshComponent plugin, which is definitely not required by OceanShader :)

**Comment by victor-vexargames** [comment]
Overall what changes happened between TK and yours? Overall I am worried about upgrading from mine which is working and trust yours more then the main branch at this point since it has been so long since the update today.

**Comment by TheZoc** [comment]
@victor-vexargames Hello,

The differences are outlines in the PR note. TL;DR, there are a many fixed warnings and issues regarding assets, removed unneeded reference to RuntimeMeshComponent and some other minor improvements.

If you just use the plugin, there are some minor code improvements for clarity and avoiding ambiguity on some parts. (This will prevent issues on different platforms other than Windows 😉 )

**Comment by StartOrigin** [comment]
Update to 4.16 with new features please

**Comment by victor-vexargames** [comment]
I am using it with 4.16 already. I had no issues with what was working in 4.15.

**Review by ghost — CHANGES_REQUESTED** [review]
Could you upload a version only with the files completely in funsion or only necessary files?

**Comment by victor-vexargames** [comment]
Hey Zoc are you still keeping your branch up to date with 4.17.1? I got a rendering issue since the switch emitters are sorting improperly.

**Comment by TheZoc** [comment]
I had updated to 4.16 without issues, but I'll check what's happening with 4.17.
Not sure if I'll be able to do that this week, but I'll probably get it done on the next one 😃

**Comment by victor-vexargames** [comment]
Thanks man, I have a sorting issue with any transparent materials or emitters using 4.17.1 they changed how some of the structures should work so the version I have been carrying over since 4.14 is having this trouble. Some people have updated the main branch but I would rather work with the striped down version with out of extra crap and have your other fixes. They should open the repo if they are not going to maintain it or get others to have merge control to keep the builds up.

**Comment by TheZoc** [comment]
Update my branch (and consequently this PR) with the following changes:
- Updated uplugin project file to the new stricter standards
- Bumped plugin internal version to 1.1
- Updated all .cs files to the latest format/version
- Updated conflicting assets
- Some code cleanup

**Comment by TheZoc** [comment]
@victor-vexargames I have updated my fork, finally. Sorry it took so long.
If you have issues, can you open an issue there? It's hard for me to help with anything here, since I don't have write access to the repository.

And, well, I've already requested access to the repo over a year ago, no reply. I remember reading something on unreal forums about they going commercial, so, it's possible that it will never happens, sadly :(

**Comment by dotcamdev** [comment]
@TheZoc - What is your UE4 forums username? I have no issue whatsoever with adding you to the repo if you want to have write access, only thing I ask is that you copy the current master branch to a new branch called something like MasterArchive before pushing new commits.

Is there anyone else who has been trying to work on the project? If so let me know, or you can just add them to the organization. I've not been able to work on this for a long time now due to spine surgeries, not being able to work at my main PC, as well as a lot of pain that makes it impossible to concentrate. I hope to be able to get back to this project soon, I'm pretty sure there won't be any more surgeries so it's just a matter of waiting until I am well enough.

TK-Master might be creating a more advanced version for the marketplace at some point, but this project will always be free & open source, so don't worry about that.

Thank you for all of the work you have done to keep this project going, and apologies for not doing this sooner. You should have access by the time you read this.

Cheers,
Cam

**Comment by dotcamdev** [comment]
@TheZoc - When you get a chance could you please PM me over on the UE4 forums, I couldn't find your account there (it is TheZoc there too isn't it?). I see you have access now, which is great! 

Just have some additional info to pass on that isn't relevant to this pull request... :)

Thanks!

**Comment by TheZoc** [comment]
@dotcamdev I sent you a message there, but not sure if it actually went. Can you check it and let me know, please? 😃

**Comment by dotcamdev** [comment]
@TheZoc I dunno what's going on with the forum pm system.. I originally got your message and replied to it, but now I can't find my reply or your original pm!!??

If you still haven't received it (I just resubmitted a new pm with a copy of my reply, luckily I didn't close that tab in my browser so I didn't have to start over),let me know and I will find a way to get you my email address!

Funny how something so simple becomes such a problem sometimes... :)

**Comment by TheZoc** [comment]
@dotcamdev I never got your PM :( - Got a small truncated version of what seems to be the last message, but I can't see it on UE4 forums.
I tried PM'ing you my email address on UE4 forums. Hopefully you can read it :)

**Comment by dotcamdev** [comment]
@TheZoc  I sent you an email this morning with a copy of the pm, did you receive it? Just wanted to make sure you got it this time! :)

**Comment by TheZoc** [comment]
@dotcamdev Got it! 😀

**Pull request merged**
