### PR TITLE
Made IWYU compliant (Include What You Use).

### PR DESCRIPTION
**Pull request by EvoPulseGaming**
Made IWYU compliant (Include What You Use)
Set PCHUsage in Build.cs to UseExplicitOrSharedPCHs
Remove unused #includes unless referenced by commented code
Added #include CoreMinimal.h and #include EngineMinimal.h where needed
Added missing #includes where needed

### CODE REVIEW

**Comment by TheZoc** [comment]
Hello @saschaelble,

This is a great PR!

I have a few requests/questions prior I can merge it:

- Why remove the [Precompiled Header](https://en.wikipedia.org/wiki/Precompiled_header) include? It really speeds things up!

- Since you're hard at work on this, can you check the possibility of adding CoreMinimal.h and/or EngineMinimal.h to the Precompiled Header? Maybe it's an even better option than including them on all of the files 😄 

- The binaries and the Screenshot must be removed before I can merge the PR

**Comment by saschaelble** [comment]
The unreal build toolstill creates the pch's, but does so in an automatic and efficient manner.

Only files NEEDING core and engine have it. It was not included in any file that didn't use it. (Very few)

The binaries are recompiled from the iwyu change... Why remove them?

I can remove the screenshot.

Let me know what you think

**Comment by saschaelble** [comment]
Coreminimal.h is for things like variables that start with F (FVector)
Engineminimal.h is for things like objects that start with F (FActor)

**Comment by EvoPulseGaming** [comment]
>
>     Why remove the Precompiled Header include? It really speeds things up!
>     Since you're hard at work on this, can you check the possibility of adding CoreMinimal.h and/or EngineMinimal.h to the Precompiled Header? Maybe it's an even better option than including them on all of the files 😄
> 
I've gone ahead and added:
     PrivatePCHHeaderFile = "Classes/OceanPluginPrivatePCH.h";
This way everyone is happy xD
>
>     The binaries and the Screenshot must be removed before I can merge the PR
> 
The binaries are recompiled from the iwyu change... Why remove them? Would it be a better option to add those binaries to the Git ignore list and add that to the commit? (Would this would force everyone to compile the plugin on first use?)

Let me know what you think

**Pull request closed without merging**
